import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@/styles/globals.css";
import { Toaster } from "@/components/ui/toaster"
// import { SpeedInsights } from "@vercel/speed-insights/next";
import { JetBrains_Mono as FontMono } from "next/font/google"
// import { GeistMono } from "geist/font/mono"
import { GeistSans } from "geist/font/sans"


 const fontSans = GeistSans

// export const fontMono = FontMono({
//   subsets: ["latin"],
//   variable: "--font-mono",
// })
// const roboto = Roboto({
//     subsets: ["latin"],
//     weight: "400",
// });

export const metadata: Metadata = {
    title: "SwiftMove",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={fontSans.className}>
                {children}
                <Toaster />
                {/* <SpeedInsights /> */}
            </body>
        </html>
    );
}
